-- Encodage
SET client_encoding TO 'UTF8';

-- Pour stopper à la première erreur
\set ON_ERROR_STOP on

-- Début de la transaction
BEGIN;

-- Suppression des tables existantes
DROP TABLE IF EXISTS Comments, Images, Steps, Sheet_theme, ActivitySheet, Users, Favoris, Theme;

-- Création des tables

CREATE TABLE Favoris (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE Users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    birthdate VARCHAR(10) NOT NULL,
    favoris_id INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    FOREIGN KEY (favoris_id) REFERENCES Favoris(id)
);

CREATE TABLE Theme (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

CREATE TABLE ActivitySheet (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    material VARCHAR(100) NOT NULL,
    name VARCHAR(50) NOT NULL,
    age VARCHAR(20) NOT NULL,
    description VARCHAR(100) NOT NULL,
    educational_objective VARCHAR(100) NOT NULL,
    user_id INTEGER NOT NULL,
    favoris_id INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    FOREIGN KEY (user_id) REFERENCES Users(id),
    FOREIGN KEY (favoris_id) REFERENCES Favoris(id)
);

CREATE TABLE Sheet_theme (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    activitySheet_id INTEGER,
    theme_id INTEGER,
    FOREIGN KEY (activitySheet_id) REFERENCES ActivitySheet(id),
    FOREIGN KEY (theme_id) REFERENCES Theme(id)
);

CREATE TABLE Steps (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(50) NOT NULL,
    description VARCHAR(100) NOT NULL,
    activitySheet_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    FOREIGN KEY (activitySheet_id) REFERENCES ActivitySheet(id)
);

CREATE TABLE Images (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    url VARCHAR(255) NOT NULL,
    activitySheet_id INTEGER,
    user_id INTEGER,
    theme_id INTEGER,
    steps_id INTEGER,
    FOREIGN KEY (activitySheet_id) REFERENCES ActivitySheet(id),
    FOREIGN KEY (user_id) REFERENCES Users(id),
    FOREIGN KEY (theme_id) REFERENCES Theme(id),
    FOREIGN KEY (steps_id) REFERENCES Steps(id)
);

CREATE TABLE Comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content VARCHAR(255) NOT NULL,
    parent_id INTEGER,
    date VARCHAR(20) NOT NULL,
    user_id INTEGER NOT NULL,
    activitySheet_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(id),
    FOREIGN KEY (activitySheet_id) REFERENCES ActivitySheet(id),
    FOREIGN KEY (parent_id) REFERENCES Comments(id)
);

-- Fin de la transaction
COMMIT;

